name: Docs

on:
  push:
    branches: [22_docs_github_action]

jobs:
  build:
    name: "Build docs to docs branch"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.13.2
      - name: Setup node ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: config commit username
        run: git config user.name $GH_USER
        env:
          GH_USER: ${{ secrets.GH_USER }}
      - name: config commit email
        run: git config user.email $GH_EMAIL
        env:
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
      - name: Build docs to docs branch

        run: pnpm exec .github/workflows/docs.sh
